spring:
  application.name: JinnMeServer
  jpa:
    hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changesets.postgres.sql
  jackson:
    default-property-inclusion: non_null
logging:
  file:
    path: /var/log/jinnme-server
    name: jinnme.log